/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class JIApprovalLeave extends javax.swing.JInternalFrame {

    /**
     * Creates new form ApprovalLeave
     */
    public JIApprovalLeave() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        detailPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        approvalTable = new javax.swing.JTable();
        detailPanel = new javax.swing.JPanel();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1080, 437));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Approval Waiting List");

        approvalTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "LEAVE_1", "Sindi", "05/01/2019"}
            },
            new String [] {
                "No", "Leave Request ID", "Requester", "Request Date"
            }
        ));
        approvalTable.setShowHorizontalLines(false);
        approvalTable.setShowVerticalLines(false);
        approvalTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                approvalTableMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                approvalTableMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(approvalTable);

        javax.swing.GroupLayout detailPanelLayout = new javax.swing.GroupLayout(detailPanel);
        detailPanel.setLayout(detailPanelLayout);
        detailPanelLayout.setHorizontalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        detailPanelLayout.setVerticalGroup(
            detailPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 189, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout detailPanel1Layout = new javax.swing.GroupLayout(detailPanel1);
        detailPanel1.setLayout(detailPanel1Layout);
        detailPanel1Layout.setHorizontalGroup(
            detailPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(detailPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(detailPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 881, Short.MAX_VALUE))
                    .addComponent(detailPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap())
        );
        detailPanel1Layout.setVerticalGroup(
            detailPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(detailPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(detailPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detailPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(detailPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void approvalTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_approvalTableMouseClicked
        DefaultTableModel model =(DefaultTableModel) approvalTable.getModel();
        int selectedRowIndex = approvalTable.getSelectedRow();
        System.out.println(selectedRowIndex);
        
        JIApprovalDetail ad = new JIApprovalDetail();
        this.detailPanel.add(ad);
        ad.show();
    }//GEN-LAST:event_approvalTableMouseClicked

    private void approvalTableMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_approvalTableMouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_approvalTableMouseReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable approvalTable;
    private javax.swing.JPanel detailPanel;
    private javax.swing.JPanel detailPanel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
